added file checks to the terraform directory and smoke test files for consistency

diff --git a/.github/workflows/deployment.yml b/.github/workflows/deployment.yml
--- a/.github/workflows/deployment.yml
+++ b/.github/workflows/deployment.yml
@@ -51,27 +51,43 @@ jobs:
           # terraform_version: 0.13.0
           cli_config_credentials_token: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}
 
+
+      ## Verify that the Terraform directory exists in the remote repo
+      - name: Check for Terraform Directory
+        id: terraform_directory
+        uses: andstor/file-existence-action@v1
+        with:
+          files: "terraform-unity"
+      - name: Terraform Directory Exists
+        if: steps.terraform_directory.outputs.files_exists != 'true'
+        run: exit 1
+
+      ## Check Terraform formatting
       - name: Terraform Format
         working-directory: ./resources/deployable/terraform-unity
         id: fmt
         run: terraform fmt -check
 
+      ## Init terraform
       - name: Terraform Init
         working-directory: ./resources/deployable/terraform-unity
         id: init
         run: terraform init
 
+      ## Validate Terraform
       - name: Terraform Validate
         working-directory: ./resources/deployable/terraform-unity
         id: validate
         run: terraform validate -no-color
 
+      ## Plan Terraform
       - name: Terraform Plan
         working-directory: ./resources/deployable/terraform-unity
         id: plan
         run: terraform plan -no-color
         continue-on-error: true
 
+      ## Fail the job if terraform plan doesn't succeed
       - name: Terraform Plan Status
         working-directory: ./resources/deployable/terraform-unity
         if: steps.plan.outcome == 'failure'
@@ -81,6 +97,18 @@ jobs:
         working-directory: ./resources/deployable/terraform-unity
 #        if: github.ref == 'refs/heads/smolenski_tf_test' && github.event_name == 'push'
         run: terraform apply -auto-approve
+
+
+      ## Verify that the smoke test exists
+      - name: Check for Smoke Tests
+        id: smoke_test_file
+        uses: andstor/file-existence-action@v1
+        with:
+          files: "terraform-unity/smoketest/smoketest.py"
+      - name: Smoke Test Exists
+        if: steps.smoke_test_file.outputs.files_exists != 'true'
+        run: exit 1
+
 
       - name: Post-Deployment Smoke Test
         uses: actions/setup-python@v2
